### ISSUE TITLE
:sparkles: **Comienzo del proyecto** :sparkles:

### ISSUE THREAD

**Issue by ShadyG98** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#1]
Re-estructuración de la nueva base de datos que constará de varias fases:
- [x] Revisar las tablas viejas
- [x] Anexar las nuevas
- [x] Re-actualizarlas
- [x] Crear el modelo final

**Comment by anaochonga** [comment]
Se realizo la revisión de las tablas del modelo anterior
![image](https://user-images.githubusercontent.com/90658364/175441505-3a8f3ba1-1a3a-4d02-b87c-34330144a586.png)

**Comment by anaochonga** [comment]
Se crean nuevas tablas que darán estructura al ecommerce.
![image](https://user-images.githubusercontent.com/90658364/175441621-9fa6cc25-5b10-4c19-ba19-888309435f9c.png)

**Comment by anaochonga** [comment]
Se sube el script de la Base de datos con las nuevas tablas

[Script_GestorStock_Ecommerce.txt](https://github.com/PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03/files/8977363/Script_GestorStock_Ecommerce.txt)

**Comment by ShadyG98** [comment]
Perfecto!! Excelente!
