### ISSUE TITLE
TSK#3 Crear componente input

### ISSUE THREAD

**Issue by O-Debegnach** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#11]
Generar un componente input (selector app-input) que represente los inputs con iconografía de los formularios

El componente debe tener como entrada:
   - titulo: `string` Titulo que se mostrará en la caja como placeholder
   - icono: `string | Icono` Indica el icono que se mostrará (definir icono por defecto en caso de ausencia)
   - tipo: `string` Indica el tipo de input pudiendo ser `text | password | text area | select`
 
Debe aceptar contenido anidado que será contenido en el input, por ejemplo:
<app-input titulo="ejemplo" tipo="text"> Hola mundo </app-input>    implica un input de tipo texto con placeholder "ejemplo", icono por defecto y value (lo que esta escrito en el input) igual a "Hola mundo"

Utilizar los estilos ya creados para los mismos

**Comment by erkcgn** [comment]
@O-Debegnach revisar mejoras realizadas.
