### ISSUE TITLE
TSK#7 Página de registro

### ISSUE THREAD

**Issue by O-Debegnach** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#16]
Migrar la página de registro a Angular.
Unificar los registros de persona y empresa en un único registro donde se agrega el campo de tipo checkbox "soy vendedor"
Los campos de información de empresa solo deben ser visibles y requeridos cuando el checkbox "soy vendedor" se encuentra tildado, caso contrario deben permanecer ocultos y no ser requeridos

**Comment by erkcgn** [comment]
@O-Debegnach se aplica lo solicitado, resta revisar validaciones en componente input para utilizarlo aquí.
