### ISSUE TITLE
DER y Modelo relacional de la Base de datos

### ISSUE THREAD

**Issue by ShadyG98** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#2]
Creación visual del Modelo relacional para la documentación de la base de datos.

- [x] Creación del modelo base del proyecto
- [x] Apartado visual del proyecto (la imagen DER pero con una herramienta visual) en imagen para documentarlo en el README

**Comment by junegrete** [comment]
![Modelo_BD_Ecommerce](https://user-images.githubusercontent.com/90485990/175749254-0c4afd90-614e-422c-b5a5-cdfd2b70874a.jpeg)

**Comment by junegrete** [comment]
Se sube Modelo relacional.

**Comment by ezedominguez** [comment]
Se da por finalizado: 
#2 | DER y Modelo relacional de la Base de datos.

**Comment by ShadyG98** [comment]
Buenísimo chicos!
