### ISSUE TITLE
Creación de Diagrama de clases para POO

### ISSUE THREAD

**Issue by ShadyG98** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#3]
Creación del modelo base en POO, comenzaremos con Java para inicializar el proyecto

- [x] Diseño del diagrama UML del proyecto en base a las clases
- [x] Creación de las posibles clases en POO

**Comment by MaxiEsc** [comment]
Diagrama de POO para ir planteando una idea de su implementacion en JAVA

![Diagrama Provisorio POO JAVA  drawio](https://user-images.githubusercontent.com/32075931/175758435-b7493b36-4936-44c1-91a6-0dd0deba4253.png)

Espero que lo vean y digan que les parece

**Comment by ShadyG98** [comment]
**NOTA:** _Se recomienda descargar la imagen para poder visualizarla correctamente, debido a que el tamaño de la imagen es bastante grande y podría causar inconvenientes al visualizarla en el navegador._

**Comment by ShadyG98** [comment]
Issue finalizada!
