### ISSUE TITLE
TSK#29 Armar datos de prueba

### ISSUE THREAD

**Issue by O-Debegnach** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#55]
Armar un json que dentro contenga un array con objetos con la siguiente estructura para cargar productos de prueba

```
{
    "idProducto": null,
    "nombreProducto": "nombre del producto",
    "idTipoProd": 1,
    "clave": "clave alfanumerica aleatoria",
    "barCode": "codigo de barras (numeros y letras)",
    "imageURL": "url de la imagen",
    "costo": numero,
    "valor": numero,
    "cantidad": stock,
    "fechaIng": null
}
```
#### Aclaracion #### 
Los campos en null deben quedar en null.
La url de la imagen puede ser comiada de cualquier imagen encontrada en google en lo posible que sea https o http (evitar las url tipo data)

**Comment by ShadyG98** [comment]
{
    "idProducto": null,
    "nombreProducto": "Galletas de agua Argentinitas",
    "idTipoProd": 1,
    "clave": "AA111BGHYJUWERD",
    "barCode": "779210311110",
    "imageURL": "https://atomoconviene.com/atomo-ecommerce/52994-home_default/galletas-d-agua-argentitas-tripack-306-grs-.jpg",
    "costo": 160,
    "valor": 150,
    "cantidad": 13,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Azucar Chango Refinado Premium 1 Kg.",
    "idTipoProd": 2,
    "clave": "AA112BGHYJUWERD",
    "barCode": "779210311120",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/717008-800-auto?v=637977297716630000&width=800&height=auto&aspect=true",
    "costo": 270,
    "valor": 254,
    "cantidad": 10,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Leche entera La serenisima 1 litro.",
    "idTipoProd": 3,
    "clave": "AA113BGHYJUWERD",
    "barCode": "779210311130",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/627635-800-auto?v=637533704023300000&width=800&height=auto&aspect=true",
    "costo": 280,
    "valor": 247,
    "cantidad": 20,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Yerba Mate Rosamonte Con Palo 1 Kg",
    "idTipoProd": 4,
    "clave": "AA114BGHYJUWERD",
    "barCode": "779210311140",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/204990-800-auto?v=636383675097730000&width=800&height=auto&aspect=true",
    "costo": 760,
    "valor": 720,
    "cantidad": 26,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Queso Cremon Cremoso La Serenisima Unidad Aprox 1 Kg",
    "idTipoProd": 5,
    "clave": "AA115BGHYJUWERD",
    "barCode": "779210311150",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/549745-800-auto?v=637051944618930000&width=800&height=auto&aspect=true",
    "costo": 1800,
    "valor": 1600,
    "cantidad": 23,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Papel Higienico Higienol Duo, Doble Hoja",
    "idTipoProd": 6,
    "clave": "AA116BGHYJUWERD",
    "barCode": "779210311160",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/708038-800-auto?v=637919626128370000&width=800&height=auto&aspect=true",
    "costo": 1000,
    "valor": 880,
    "cantidad": 24,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Fideos Spaghetti Matarazzo X500 Gr",
    "idTipoProd": 7,
    "clave": "AA117BGHYJUWERD",
    "barCode": "779210311170",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/708038-800-auto?v=637919626128370000&width=800&height=auto&aspect=true",
    "costo": 230,
    "valor": 207,
    "cantidad": 21,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Cafe La Virginia Molido 500gr",
    "idTipoProd": 8,
    "clave": "AA118BGHYJUWERD",
    "barCode": "779210311180",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/646156-800-auto?v=637582880095270000&width=800&height=auto&aspect=true",
    "costo": 1090,
    "valor": 1083,
    "cantidad": 19,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Jugo Cepita Del Valle 25% Multifruta 1 Lt",
    "idTipoProd": 9,
    "clave": "AA119BGHYJUWERD",
    "barCode": "779210311190",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/708284-800-auto?v=637921138357770000&width=800&height=auto&aspect=true",
    "costo": 260,
    "valor": 245,
    "cantidad": 12,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Shampoo Head Shoulders Proteccion Caida Con Cafeina 375 Ml",
    "idTipoProd": 10,
    "clave": "AA121BGHYJUWERD",
    "barCode": "779210311210",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/672609-800-auto?v=637707837883600000&width=800&height=auto&aspect=true",
    "costo": 2000,
    "valor": 2098,
    "cantidad": 6,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Manteca Sancor Multivitaminas 200 Gr",
    "idTipoProd": 11,
    "clave": "AA122BGHYJUWERD",
    "barCode": "779210311220",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/192147-800-auto?v=636383528822100000&width=800&height=auto&aspect=true",
    "costo": 360,
    "valor": 353,
    "cantidad": 8,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Aderezo Mayonesa Natura 475 Gr",
    "idTipoProd": 12,
    "clave": "AA123BGHYJUWERD",
    "barCode": "779210311230",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/685480-800-auto?v=637786569809200000&width=800&height=auto&aspect=true",
    "costo": 280,
    "valor": 268,
    "cantidad": 11,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Sal Fina Dos Anclas Trilaminado 500 Gr",
    "idTipoProd": 13,
    "clave": "AA124BGHYJUWERD",
    "barCode": "779210311240",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/188583-800-auto?v=636383496216030000&width=800&height=auto&aspect=true",
    "costo": 106,
    "valor": 212,
    "cantidad": 13,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Huevo Blanco Carton X6u Santa Rita",
    "idTipoProd": 14,
    "clave": "AA125BGHYJUWERD",
    "barCode": "779210311250",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/704400-800-auto?v=637897918104970000&width=800&height=auto&aspect=true",
    "costo": 308,
    "valor": 300,
    "cantidad": 20,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Aceite Girasol Pureza 0,9 L",
    "idTipoProd": 15,
    "clave": "AA126BGHYJUWERD",
    "barCode": "779210311260",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/591712-800-auto?v=637290848777400000&width=800&height=auto&aspect=true",
    "costo": 470,
    "valor": 452,
    "cantidad": 22,
    "fechaIng": null
}


{
    "idProducto": null,
    "nombreProducto": "Harina Pureza Para Pizza 1 Kg",
    "idTipoProd": 16,
    "clave": "AA128BGHYJUWERD",
    "barCode": "779210311280",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/538468-800-auto?v=636983688363000000&width=800&height=auto&aspect=true",
    "costo": 220,
    "valor": 203,
    "cantidad": 32,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Lavandina Ayudin Clasica 1lt",
    "idTipoProd": 17,
    "clave": "AA129BGHYJUWERD",
    "barCode": "779210311290",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/678965-800-auto?v=637739051408200000&width=800&height=auto&aspect=true",
    "costo": 160,
    "valor": 151,
    "cantidad": 21,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Arroz Oro Estuche Gallo X1 Kg",
    "idTipoProd": 18,
    "clave": "AA131BGHYJUWERD",
    "barCode": "779210311310",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/601814-800-auto?v=637352619948700000&width=800&height=auto&aspect=true",
    "costo": 280,
    "valor": 271,
    "cantidad": 15,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Pure De Papas Maggic Cremoso Flowpack X200gr",
    "idTipoProd": 19,
    "clave": "AA132BGHYJUWERD",
    "barCode": "779210311320",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/704791-800-auto?v=637901266599630000&width=800&height=auto&aspect=true",
    "costo": 390,
    "valor": 387,
    "cantidad": 19,
    "fechaIng": null
}

{
    "idProducto": null,
    "nombreProducto": "Fosforos Tres Patitos",
    "idTipoProd": 20,
    "clave": "AA133BGHYJUWERD",
    "barCode": "779210311330",
    "imageURL": "https://jumboargentina.vtexassets.com/arquivos/ids/662594-800-auto?v=637661398122700000&width=800&height=auto&aspect=true",
    "costo": 200,
    "valor": 155,
    "cantidad": 12,
    "fechaIng": null
}

**Comment by ShadyG98** [comment]
Dejo 20 ejemplos, si faltan mas, avisen.
