### ISSUE TITLE
TSK#1 Migrar componente Login

### ISSUE THREAD

**Issue by O-Debegnach** [PPROF2-2022ProgWeb/g03-aula1-gestorstock-g03#7]
- Migrar la página de login que actualmente esta en HTML a Angular. (únicamente el cuerpo)
- Implementar validaciones de formato en tiempo en el formulario
     1. Validaciones de formato para email (Regexp /[a-z0-9]{4,}@[a-z0-9]{4,}\.[a-z]{2,}/gi )
     2. Validación de largo de cadena para password

- Si el formulario es valido, habilitar el botón de login, caso contrario debe permanecer deshabilitado
- La acciona de logueo debe redirigir a la ruta "/dashboard"

**Comment by erkcgn** [comment]
@O-Debegnach revisar avances ya que esta en un 90% realizado

**Comment by O-Debegnach** [comment]
@erkcgn Loas avances estan bien, solo hay que corregir un par de cosas.

- [x] El boton de login deberia se siempre visible solo que si el formulario no es valido deberia tener el atributo disabled

- [x] La condicion para la activacion del boton de login deberia ser si Password es valido y si Email es valido en lugar de si tienen valor, de lo contrario se puede enviar el formulario simplemente poniendo una letra en cada campo
- [x] Fijate si hay forma de achicar el margen entre la caja de texto y el mensaje de error

Lo de los iconos no te preocupes lo arreglamos despues cuando fusionemos las ramas

**Comment by erkcgn** [comment]
@O-Debegnach revisar modificaciones; no aplique cambios sobre margen solicitado ya que tendría que modificar el div completo por el input-conteiner.

**Comment by erkcgn** [comment]
@O-Debegnach revisar ya que se ha aplicado todo lo requerido.
